export type EnrollmentPayload = {
  base_url: string;
  api_key: string;
  model: string;
  models: string[];
  expires_at: number;
  import_status_path?: string;
};

export type StreamDelta =
  | { type: "text"; text: string }
  | { type: "tool"; index: number; id?: string; name?: string; arguments?: string };

export function normalizeBaseUrl(value: string): string {
  const url = new URL(value.trim());
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new Error("HiMind Base URL must use HTTP or HTTPS");
  }
  url.search = "";
  url.hash = "";
  return url.toString().replace(/\/$/, "");
}

export function parseEnrollmentUri(uri: URL): { port: number; code: string } {
  if (uri.protocol !== "vscode:" || uri.hostname !== "himind.himind-ai") {
    throw new Error("Unsupported HiMind enrollment link");
  }
  const segments = uri.pathname.split("/").filter(Boolean);
  let portValue: string | null = null;
  let code = "";
  if (segments.length === 3 && segments[0] === "enroll") {
    [, portValue, code] = segments;
  } else if (uri.pathname === "/enroll") {
    // Kept for links generated by Agent versions before the path-only protocol.
    portValue = uri.searchParams.get("port");
    code = uri.searchParams.get("code") ?? "";
  } else {
    throw new Error("Unsupported HiMind enrollment link");
  }
  const port = Number(portValue);
  if (!Number.isInteger(port) || port < 1024 || port > 65535) {
    throw new Error("Invalid HiMind Agent port");
  }
  if (code.length < 32 || !/^[A-Za-z0-9]+$/.test(code)) {
    throw new Error("Invalid HiMind enrollment code");
  }
  return { port, code };
}

export function parseModelCatalog(payload: unknown): string[] {
  if (!payload || typeof payload !== "object" || !("data" in payload) || !Array.isArray(payload.data)) {
    throw new Error("HiMind returned an invalid model catalog");
  }
  const models: string[] = [];
  const seen = new Set<string>();
  for (const item of payload.data) {
    if (!item || typeof item !== "object" || !("id" in item) || typeof item.id !== "string") continue;
    const id = item.id.trim();
    if (!id || seen.has(id)) continue;
    seen.add(id);
    models.push(id);
  }
  if (!models.length) throw new Error("HiMind returned an empty model catalog");
  return models;
}

export function parseSseEvent(block: string): StreamDelta[] {
  const data = block
    .split(/\r?\n/)
    .filter((line) => line.startsWith("data:"))
    .map((line) => line.slice(5).trimStart())
    .join("\n");
  if (!data || data === "[DONE]") return [];
  const payload = JSON.parse(data) as { choices?: Array<{ delta?: { content?: string; tool_calls?: Array<{ index?: number; id?: string; function?: { name?: string; arguments?: string } }> } }> };
  const delta = payload.choices?.[0]?.delta;
  const result: StreamDelta[] = [];
  if (delta?.content) result.push({ type: "text", text: delta.content });
  for (const call of delta?.tool_calls ?? []) {
    result.push({
      type: "tool",
      index: call.index ?? 0,
      id: call.id,
      name: call.function?.name,
      arguments: call.function?.arguments,
    });
  }
  return result;
}
